// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.8.0
// source: pkg/config/po/file.proto

package po

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type FRq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 当前机器号
	DeviceId string `protobuf:"bytes,1,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	// 当先exe版本号
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// 客户端类型
	Model string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *FRq) Reset() {
	*x = FRq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_config_po_file_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FRq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FRq) ProtoMessage() {}

func (x *FRq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_config_po_file_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FRq.ProtoReflect.Descriptor instead.
func (*FRq) Descriptor() ([]byte, []int) {
	return file_pkg_config_po_file_proto_rawDescGZIP(), []int{0}
}

func (x *FRq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *FRq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *FRq) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type FRp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 服务器是否处理成功
	Code int64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 是否需要下载
	Need bool `protobuf:"varint,2,opt,name=need,proto3" json:"need,omitempty"`
	// 下载地址
	FilePath string `protobuf:"bytes,3,opt,name=filePath,proto3" json:"filePath,omitempty"`
}

func (x *FRp) Reset() {
	*x = FRp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_config_po_file_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FRp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FRp) ProtoMessage() {}

func (x *FRp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_config_po_file_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FRp.ProtoReflect.Descriptor instead.
func (*FRp) Descriptor() ([]byte, []int) {
	return file_pkg_config_po_file_proto_rawDescGZIP(), []int{1}
}

func (x *FRp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FRp) GetNeed() bool {
	if x != nil {
		return x.Need
	}
	return false
}

func (x *FRp) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

var File_pkg_config_po_file_proto protoreflect.FileDescriptor

var file_pkg_config_po_file_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x70, 0x6f, 0x2f,
	0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x51, 0x0a, 0x03, 0x46, 0x52,
	0x71, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x49, 0x0a,
	0x03, 0x46, 0x52, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x65, 0x65, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6e, 0x65, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x42, 0x34, 0x0a, 0x1b, 0x6f, 0x72, 0x67, 0x2e,
	0x6a, 0x65, 0x65, 0x63, 0x67, 0x2e, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2e, 0x76, 0x70,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x06, 0x52, 0x65, 0x50, 0x6f, 0x6a, 0x6f, 0x5a,
	0x0d, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x70, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_config_po_file_proto_rawDescOnce sync.Once
	file_pkg_config_po_file_proto_rawDescData = file_pkg_config_po_file_proto_rawDesc
)

func file_pkg_config_po_file_proto_rawDescGZIP() []byte {
	file_pkg_config_po_file_proto_rawDescOnce.Do(func() {
		file_pkg_config_po_file_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_config_po_file_proto_rawDescData)
	})
	return file_pkg_config_po_file_proto_rawDescData
}

var file_pkg_config_po_file_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_config_po_file_proto_goTypes = []interface{}{
	(*FRq)(nil), // 0: FRq
	(*FRp)(nil), // 1: FRp
}
var file_pkg_config_po_file_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_config_po_file_proto_init() }
func file_pkg_config_po_file_proto_init() {
	if File_pkg_config_po_file_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_config_po_file_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FRq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_config_po_file_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FRp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_config_po_file_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_config_po_file_proto_goTypes,
		DependencyIndexes: file_pkg_config_po_file_proto_depIdxs,
		MessageInfos:      file_pkg_config_po_file_proto_msgTypes,
	}.Build()
	File_pkg_config_po_file_proto = out.File
	file_pkg_config_po_file_proto_rawDesc = nil
	file_pkg_config_po_file_proto_goTypes = nil
	file_pkg_config_po_file_proto_depIdxs = nil
}
